name: ApesTogetherStrong
version: 1.0.0
main: dev.k41j0.ApesTogetherStrong
description: Working together has never been easier (or more vital!).
author: K41J0
api-version: '1.21'
commands:
  ats:
    description: Execute ApesTogetherStrong commands
    permission: 'ats.*'
    permission-message: '[ATS] You do not have sufficient permissions to run this command!'
permissions:
  ats.*:
    description: Grants the ability to run ATS commands.
    default: op
    children:
      ats.reload: true
  ats.reload:
    description: Grants the ability to run the ATS Reload command.
    default: op